FROM openjdk:8u181-jdk AS builder
COPY ./voter-service ./usr/local/voter-service
WORKDIR /usr/local/voter-service
RUN ./gradlew clean build -x test

FROM openjdk:8u201-jre-alpine3.9
COPY --from=builder /usr/local/voter-service/build/libs/voter-service-0.2.0.jar .
EXPOSE 8099
CMD ["java", "-jar", "./voter-service-0.2.0.jar", "--spring.data.mongodb.host=voter-mongo"]